# Traffic Routing Configuration with Feature Flags
# Supports shadow → gray-scale → full-scale promotion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-routing-config
  namespace: platform-control-plane
data:
  routing-config.yaml: |
    # Traffic Routing Rules
    routing:
      # Default: All traffic to V2
      default_version: v2
      
      # Shadow traffic configuration
      shadow:
        enabled: true
        targets:
          - version: v1
            percentage: 100  # Mirror 100% to V1
            headers:
              X-Shadow-Request: "true"
              X-Evaluation-Mode: "shadow"
          - version: v3
            percentage: 10   # Optional: Mirror 10% to V3 for comparison
            headers:
              X-Shadow-Request: "true"
              X-Comparison-Mode: "legacy"
      
      # Feature flag overrides
      feature_flags:
        # Admin can force V1 with header
        - name: x-exp-v1
          header: x-exp
          value: v1
          action:
            route_to: v1
            return_response: false  # Shadow only
        
        # Internal testing with response
        - name: x-test-v1
          header: x-test
          value: v1
          action:
            route_to: v1
            return_response: true
          whitelist:
            - "10.0.0.0/8"
      
      # Gray-scale phases (controlled by lifecycle-controller)
      grayscale:
        phases:
          - name: shadow
            v1_percentage: 100  # Shadow only
            v2_percentage: 100  # All real traffic
            return_v1_response: false
          
          - name: gray-1-percent
            v1_percentage: 1
            v2_percentage: 99
            return_v1_response: true  # Start returning V1 responses
          
          - name: gray-5-percent
            v1_percentage: 5
            v2_percentage: 95
            return_v1_response: true
          
          - name: gray-25-percent
            v1_percentage: 25
            v2_percentage: 75
            return_v1_response: true
          
          - name: gray-50-percent
            v1_percentage: 50
            v2_percentage: 50
            return_v1_response: true
          
          - name: full-rollout
            v1_percentage: 100  # Becomes new V2
            v2_percentage: 0
            return_v1_response: true

    # Request matching rules
    matching:
      # Route specific paths differently
      paths:
        - pattern: "/api/v1/analyze/security/*"
          priority: high
          v2_only: true  # Security-critical, V2 only
        
        - pattern: "/api/v1/analyze/experimental/*"
          experimental: true
          prefer_v1: true
      
      # Route based on user tier
      user_tiers:
        - tier: enterprise
          slo_strict: true
          v2_only: true
        
        - tier: free
          allow_shadow: true
          allow_experimental: true

    # Health-based routing
    health:
      check_interval: 10s
      unhealthy_threshold: 3
      healthy_threshold: 2
      
      # Fallback chain
      fallback:
        - v2  # Primary
        - v1  # If V2 unhealthy
        # V3 is never a fallback for user traffic
---
# Flagsmith Feature Flag Integration
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags-config
  namespace: platform-control-plane
data:
  flagsmith-config.yaml: |
    flagsmith:
      api_url: "https://flagsmith.example.com/api/v1"
      environment_key: "${FLAGSMITH_ENV_KEY}"
      
      flags:
        # Shadow traffic percentage
        - name: shadow_traffic_v1_percentage
          default: 100
          type: integer
          description: "Percentage of traffic to mirror to V1"
        
        # Gray-scale percentage
        - name: grayscale_v1_percentage
          default: 0
          type: integer
          description: "Percentage of real traffic to route to V1"
        
        # Enable V3 comparison
        - name: enable_v3_comparison
          default: false
          type: boolean
          description: "Mirror traffic to V3 for comparison"
        
        # Emergency rollback
        - name: emergency_rollback_to_v2
          default: false
          type: boolean
          description: "Emergency: Route all traffic back to V2"
        
        # A/B testing segments
        - name: ab_test_new_model
          default: false
          type: boolean
          segments:
            - internal_users
            - beta_testers
