apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-service
  namespace: stable-v2
spec:
  replicas: 3
  strategy:
    canary:
      canaryService: sample-service-canary
      stableService: sample-service-stable
      steps:
        - setWeight: 10
        - pause: {duration: 5m}
        - setWeight: 30
        - pause: {duration: 5m}
        - setWeight: 60
        - pause: {duration: 5m}
        - setWeight: 100
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: sample
          image: sample:latest
          ports:
            - containerPort: 3000

