apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-services
  namespace: observability
spec:
  selector: {}
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      interval: 30s
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: platform-sre
  namespace: observability
spec:
  json: |
    {
      "title": "Platform SRE",
      "panels": []
    }

