/**
 * 三版本演化服务 API (Three-Version Evolution Service API)
 *
 * 功能描述:
 *   三版本自演化循环 API 客户端。
 *
 * 版本说明:
 *   - V1（新版）: 实验，试错
 *   - V2（稳定版）: 生产，修复 V1 错误
 *   - V3（旧版）: 隔离，比较，排除
 *
 * 主要方法:
 *   - getCycleStatus(): 获取循环状态
 *   - startCycle(): 启动循环
 *   - stopCycle(): 停止循环
 *   - promoteVersion(): 升级版本
 *   - degradeVersion(): 降级版本
 *
 * 最后修改日期: 2024-12-07
 */

import { api } from "./api";

// Use api as apiClient alias for compatibility
const apiClient = api;

const API_BASE = "/api/v1/evolution";

// =============================================================================
// Types
// =============================================================================

export interface CycleStatus {
  running: boolean;
  current_cycle?: {
    cycle_id: string;
    phase: string;
    started_at: string;
    experiments_run: number;
    errors_fixed: number;
    promotions_made: number;
    degradations_made: number;
    last_activity: string;
  };
  pending?: {
    promotions: number;
    degradations: number;
    reevaluations: number;
  };
  ai_status?: Record<string, VersionAIStatus>;
  feedback_stats?: FeedbackStats;
  quarantine_stats?: QuarantineStats;
}

export interface VersionAIStatus {
  vc_ai: AIInstanceStatus;
  cr_ai: AIInstanceStatus;
}

export interface AIInstanceStatus {
  status: "active" | "degraded" | "offline" | "maintenance";
  access_level: string;
  request_count: number;
  error_rate: number;
  avg_latency_ms: number;
  capabilities: string[];
}

export interface FeedbackStats {
  total_errors_reported: number;
  total_fixes_generated: number;
  fixes_verified: number;
  fixes_failed: number;
  fix_success_rate: number;
  fix_templates_learned: number;
  error_patterns_recorded: number;
}

export interface QuarantineStats {
  total_quarantined: number;
  permanent_exclusions: number;
  temporary_exclusions: number;
  by_reason: Record<string, number>;
  by_decision: Record<string, number>;
  failure_patterns_recorded: number;
  exclusion_rules: number;
}

export interface FailureInsight {
  category: string;
  failure_count: number;
  common_reasons: string[];
  avg_accuracy: number;
  insight: string;
}

export interface ErrorReportRequest {
  tech_id: string;
  tech_name: string;
  error_type:
    | "compatibility"
    | "performance"
    | "security"
    | "accuracy"
    | "stability";
  description: string;
  stack_trace?: string;
  context?: Record<string, unknown>;
}

export interface PromotionRequest {
  tech_id: string;
  reason?: string;
}

export interface DegradationRequest {
  tech_id: string;
  reason: string;
}

export interface ReEvaluationRequest {
  tech_id: string;
  reason?: string;
}

export interface CycleHistoryEntry {
  cycle_id: string;
  started_at: string;
  completed_at?: string;
  experiments_run: number;
  errors_fixed: number;
  promotions_made: number;
  degradations_made: number;
}

export interface V2Fix {
  fix_id: string;
  error_id: string;
  fix_type: string;
  status: string;
}

// =============================================================================
// API Functions
// =============================================================================

/**
 * Get the current status of the evolution cycle
 */
export async function getCycleStatus(): Promise<CycleStatus> {
  const response = await apiClient.get<{ spiral_status: CycleStatus }>(
    `${API_BASE}/status`
  );
  return response.data.spiral_status;
}

/**
 * Start the evolution cycle
 */
export async function startCycle(): Promise<{
  success: boolean;
  message: string;
}> {
  const response = await apiClient.post<{ success: boolean; message: string }>(
    `${API_BASE}/start`
  );
  return response.data;
}

/**
 * Stop the evolution cycle
 */
export async function stopCycle(): Promise<{
  success: boolean;
  message: string;
}> {
  const response = await apiClient.post<{ success: boolean; message: string }>(
    `${API_BASE}/stop`
  );
  return response.data;
}

/**
 * Report a V1 error for V2 to analyze and fix
 */
export async function reportV1Error(
  request: ErrorReportRequest
): Promise<{ success: boolean; error_id: string }> {
  const response = await apiClient.post<{ success: boolean; error_id: string }>(
    `${API_BASE}/v1/errors`,
    request
  );
  return response.data;
}

/**
 * Get list of V1 experiments
 */
export async function getV1Experiments(): Promise<{
  version: string;
  experiments: number;
  ai_status: VersionAIStatus;
}> {
  const response = await apiClient.get(`${API_BASE}/v1/experiments`);
  return response.data;
}

/**
 * Get V2 production status
 */
export async function getV2Status(): Promise<{
  version: string;
  user_ai_status: AIInstanceStatus;
  description: string;
}> {
  const response = await apiClient.get(`${API_BASE}/v2/status`);
  return response.data;
}

/**
 * Get list of fixes generated by V2
 */
export async function getV2Fixes(): Promise<{
  statistics: FeedbackStats;
  pending_fixes: V2Fix[];
}> {
  const response = await apiClient.get(`${API_BASE}/v2/fixes`);
  return response.data;
}

/**
 * Get V3 quarantine status
 */
export async function getV3QuarantineStatus(): Promise<{
  version: string;
  statistics: QuarantineStats;
  exclusions: { permanent: string[]; temporary: string[] };
  insights: FailureInsight[];
}> {
  const response = await apiClient.get(`${API_BASE}/v3/quarantine`);
  return response.data;
}

/**
 * Get list of excluded technologies
 */
export async function getExclusionList(): Promise<{
  permanent: string[];
  temporary: string[];
}> {
  const response = await apiClient.get(`${API_BASE}/v3/exclusions`);
  return response.data;
}

/**
 * Trigger promotion of a technology from V1 to V2
 */
export async function triggerPromotion(
  request: PromotionRequest
): Promise<{ success: boolean; tech_id: string; status: string }> {
  const response = await apiClient.post(`${API_BASE}/promote`, request);
  return response.data;
}

/**
 * Trigger degradation of a technology from V2 to V3
 */
export async function triggerDegradation(
  request: DegradationRequest
): Promise<{ success: boolean; tech_id: string; status: string }> {
  const response = await apiClient.post(`${API_BASE}/degrade`, request);
  return response.data;
}

/**
 * Request re-evaluation of a quarantined technology
 */
export async function requestReEvaluation(
  request: ReEvaluationRequest
): Promise<{ success: boolean; tech_id: string; status: string }> {
  const response = await apiClient.post(`${API_BASE}/reeval`, request);
  return response.data;
}

/**
 * Get status of all AI instances across versions
 */
export async function getAllAIStatus(): Promise<
  Record<string, VersionAIStatus>
> {
  const response = await apiClient.get(`${API_BASE}/ai/status`);
  return response.data;
}

/**
 * Get status of user-accessible AI (V2 CR-AI only)
 */
export async function getUserAIStatus(): Promise<AIInstanceStatus> {
  const response = await apiClient.get(`${API_BASE}/ai/user`);
  return response.data;
}

/**
 * Get cycle history
 */
export async function getCycleHistory(limit: number = 10): Promise<{
  cycles: CycleHistoryEntry[];
}> {
  const response = await apiClient.get(`${API_BASE}/history`, {
    params: { limit },
  });
  return response.data;
}

/**
 * Get comprehensive evolution metrics
 */
export async function getEvolutionMetrics(): Promise<{
  running: boolean;
  spiral_status: CycleStatus["current_cycle"];
  feedback_stats: FeedbackStats;
  quarantine_stats: QuarantineStats;
  ai_status: Record<string, VersionAIStatus>;
}> {
  const response = await apiClient.get(`${API_BASE}/metrics`);
  return response.data;
}

/**
 * Health check for the evolution service
 */
export async function healthCheck(): Promise<{
  status: string;
  service: string;
  cycle_running: boolean;
  timestamp: string;
}> {
  const response = await apiClient.get(`${API_BASE}/health`);
  return response.data;
}

// =============================================================================
// React Query Hooks (optional - if using React Query)
// =============================================================================

export const threeVersionQueryKeys = {
  status: ["three-version", "status"] as const,
  v1Experiments: ["three-version", "v1", "experiments"] as const,
  v2Status: ["three-version", "v2", "status"] as const,
  v2Fixes: ["three-version", "v2", "fixes"] as const,
  v3Quarantine: ["three-version", "v3", "quarantine"] as const,
  exclusions: ["three-version", "v3", "exclusions"] as const,
  aiStatus: ["three-version", "ai", "status"] as const,
  userAI: ["three-version", "ai", "user"] as const,
  history: (limit: number) => ["three-version", "history", limit] as const,
  metrics: ["three-version", "metrics"] as const,
  health: ["three-version", "health"] as const,
};

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Get phase display name
 */
export function getPhaseDisplayName(phase: string): string {
  const phaseNames: Record<string, string> = {
    experimentation: "Experimentation",
    error_remediation: "Error Remediation",
    evaluation: "Evaluation",
    promotion: "Promotion",
    stabilization: "Stabilization",
    degradation: "Degradation",
    comparison: "Comparison",
    re_evaluation: "Re-evaluation",
    idle: "Idle",
  };
  return phaseNames[phase] || phase;
}

/**
 * Get error type display name
 */
export function getErrorTypeDisplayName(errorType: string): string {
  const errorTypes: Record<string, string> = {
    compatibility: "Compatibility Issue",
    performance: "Performance Problem",
    security: "Security Vulnerability",
    accuracy: "Accuracy Below Threshold",
    stability: "Stability Issue",
  };
  return errorTypes[errorType] || errorType;
}

/**
 * Get AI status color
 */
export function getAIStatusColor(
  status: string
): "success" | "warning" | "error" | "default" {
  switch (status) {
    case "active":
      return "success";
    case "degraded":
      return "warning";
    case "offline":
    case "maintenance":
      return "error";
    default:
      return "default";
  }
}

/**
 * Format success rate as percentage
 */
export function formatSuccessRate(rate: number): string {
  return `${(rate * 100).toFixed(1)}%`;
}

/**
 * Check if cycle is healthy
 */
export function isCycleHealthy(status: CycleStatus): boolean {
  if (!status.running) return false;
  if (!status.ai_status) return false;

  // Check if all AIs are active
  for (const version of Object.values(status.ai_status)) {
    if (
      version.vc_ai.status !== "active" ||
      version.cr_ai.status !== "active"
    ) {
      return false;
    }
  }

  return true;
}

// =============================================================================
// Alternative Dev API Methods (uses /api/three-version/* endpoints)
// These provide fallback when the full evolution API is not available
// =============================================================================

const DEV_API_BASE = "/api/three-version";

/**
 * Get three-version status from dev API
 */
export async function getDevStatus() {
  try {
    const response = await apiClient.get(`${DEV_API_BASE}/status`);
    return response.data;
  } catch {
    // Return mock data if API fails
    return {
      cycle_running: true,
      current_phase: "monitoring",
      v1_status: { active_experiments: 0 },
      v2_status: { active_models: 0 },
      v3_status: { quarantined_models: 0 },
    };
  }
}

/**
 * Get three-version metrics from dev API
 */
export async function getDevMetrics() {
  try {
    const response = await apiClient.get(`${DEV_API_BASE}/metrics`);
    return response.data;
  } catch {
    return { v1: {}, v2: {}, v3: {} };
  }
}

/**
 * Get experiments from dev API
 */
export async function getDevExperiments() {
  try {
    const response = await apiClient.get(`${DEV_API_BASE}/experiments`);
    return response.data;
  } catch {
    return { items: [], total: 0 };
  }
}

/**
 * Get version history from dev API
 */
export async function getDevHistory() {
  try {
    const response = await apiClient.get(`${DEV_API_BASE}/history`);
    return response.data;
  } catch {
    return { items: [], total: 0 };
  }
}

/**
 * Promote model via dev API
 */
export async function devPromote(modelId: string, reason: string) {
  const response = await apiClient.post(`${DEV_API_BASE}/promote`, null, {
    params: { model_id: modelId, reason },
  });
  return response.data;
}

/**
 * Demote model via dev API
 */
export async function devDemote(modelId: string, reason: string) {
  const response = await apiClient.post(`${DEV_API_BASE}/demote`, null, {
    params: { model_id: modelId, reason },
  });
  return response.data;
}

/**
 * Re-evaluate model via dev API
 */
export async function devReevaluate(modelId: string) {
  const response = await apiClient.post(`${DEV_API_BASE}/reevaluate`, null, {
    params: { model_id: modelId },
  });
  return response.data;
}
