# Model Registry - Versioned and Signed AI Models
# All models must be registered here before use
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-registry
  namespace: platform-control-plane
  labels:
    component: ai-core
    type: registry
data:
  models.yaml: |
    models:
      # GPT-4 Models
      - id: gpt-4-turbo
        provider: openai
        version: "2024-04-09"
        signature: "sha256:abc123..."
        capabilities:
          - code-review
          - architecture-analysis
          - security-audit
          - documentation
        constraints:
          max_tokens: 128000
          cost_per_1k_input: 0.01
          cost_per_1k_output: 0.03
          rate_limit_rpm: 500
          rate_limit_tpm: 450000
        slo:
          p95_latency_ms: 3000
          availability: 99.9
        status: active
        allowed_versions: [v1, v2]
        
      - id: gpt-4o
        provider: openai
        version: "2024-05-13"
        signature: "sha256:def456..."
        capabilities:
          - code-review
          - architecture-analysis
          - security-audit
          - documentation
          - multimodal
        constraints:
          max_tokens: 128000
          cost_per_1k_input: 0.005
          cost_per_1k_output: 0.015
          rate_limit_rpm: 10000
          rate_limit_tpm: 800000
        slo:
          p95_latency_ms: 2000
          availability: 99.9
        status: active
        allowed_versions: [v1, v2]
      
      # Claude Models
      - id: claude-3-opus
        provider: anthropic
        version: "2024-02-29"
        signature: "sha256:ghi789..."
        capabilities:
          - code-review
          - architecture-analysis
          - security-audit
          - long-context
        constraints:
          max_tokens: 200000
          cost_per_1k_input: 0.015
          cost_per_1k_output: 0.075
          rate_limit_rpm: 50
          rate_limit_tpm: 200000
        slo:
          p95_latency_ms: 5000
          availability: 99.5
        status: active
        allowed_versions: [v1, v2]
        
      - id: claude-3-5-sonnet
        provider: anthropic
        version: "2024-06-20"
        signature: "sha256:jkl012..."
        capabilities:
          - code-review
          - architecture-analysis
          - security-audit
          - documentation
        constraints:
          max_tokens: 200000
          cost_per_1k_input: 0.003
          cost_per_1k_output: 0.015
          rate_limit_rpm: 1000
          rate_limit_tpm: 400000
        slo:
          p95_latency_ms: 2500
          availability: 99.9
        status: active
        allowed_versions: [v1, v2]
      
      # Local Models (for V3 and fallback)
      - id: codellama-34b
        provider: local
        version: "2.0.0"
        signature: "sha256:mno345..."
        capabilities:
          - code-review
          - basic-analysis
        constraints:
          max_tokens: 16384
          cost_per_1k_input: 0.0001
          cost_per_1k_output: 0.0001
          rate_limit_rpm: 10000
        slo:
          p95_latency_ms: 500
          availability: 99.99
        status: active
        allowed_versions: [v1, v2, v3]
        
      - id: deepseek-coder-33b
        provider: local
        version: "1.5.0"
        signature: "sha256:pqr678..."
        capabilities:
          - code-review
          - code-completion
        constraints:
          max_tokens: 16384
          cost_per_1k_input: 0.0001
          cost_per_1k_output: 0.0001
        status: active
        allowed_versions: [v1, v2, v3]

    # Model groups for cascading
    model_groups:
      - name: primary-cascade
        description: "Primary model cascade for production"
        models:
          - gpt-4o
          - claude-3-5-sonnet
          - codellama-34b
        timeout_cascade_ms: [3000, 5000, 2000]
        
      - name: security-focused
        description: "Models optimized for security analysis"
        models:
          - claude-3-opus
          - gpt-4-turbo
        timeout_cascade_ms: [5000, 5000]
        
      - name: cost-optimized
        description: "Cost-effective model selection"
        models:
          - codellama-34b
          - deepseek-coder-33b
          - claude-3-5-sonnet
        timeout_cascade_ms: [2000, 2000, 3000]

    # Version-specific model assignments
    version_assignments:
      v1:
        default_group: primary-cascade
        experimental_models:
          - gpt-4o
          - claude-3-5-sonnet
      v2:
        default_group: primary-cascade
        restricted_models:
          - codellama-34b  # Only as fallback
      v3:
        default_group: cost-optimized
        allowed_models:
          - codellama-34b
          - deepseek-coder-33b
